### ISSUE TITLE
[localai-git] strip off leading `v` from `$pkgver`.

### ISSUE THREAD

**Issue by dreirund** [wuxxin/aur-packages#6]
Please strip off the leading `v` from `$pkgver` in `localai-git`, as required by the [Arch Linux VCS package guidelines](https://wiki.archlinux.org/title/VCS_package_guidelines#Git).

Regards and thanks for maintaining!

**Comment by wuxxin** [comment]
https://github.com/wuxxin/aur-packages/commit/4496023c48e956e59b4d19b5f44d389a3826502a
