### ISSUE TITLE
[localai-git] You need to remove `../` in `pkgver()`. It fails with `../localai: No such file or directory`.

### ISSUE THREAD

**Issue by dreirund** [wuxxin/aur-packages#8]
in the [`PKGBUILD` of `localai-git`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=localai-git) you reference directories that are above `$srcdir`.

This must never be done. It is not guarantueed where this leads to, when the user has `$SRCDEST` set in `/etc/makepkg.conf` or the local environment.

This leads to an error in `pkgver()`:  
```
==> Starting pkgver()...
/tmp/makepkg/yay/localai-git/PKGBUILD: line 100: cd: /tmp/makepkg/build/localai-git/src/../localai: No such file or directory
==> ERROR: A failure occurred in pkgver().
```

Please replace `"${srcdir}/../${_pkgname}"` with `"${srcdir}/${_pkgname}"`.

Regards and thanks for maintaining!

**Comment by wuxxin** [comment]
https://github.com/wuxxin/aur-packages/commit/4496023c48e956e59b4d19b5f44d389a3826502a
